# Generated by Django 5.2.11 on 2026-03-07 04:47

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models

from netbox_pathways.geo import get_srid

_SRID = get_srid()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dcim', '0226_add_mptt_tree_indexes'),
        ('extras', '0134_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pathway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('pathway_type', models.CharField(editable=False, max_length=50)),
                ('path', django.contrib.gis.db.models.fields.LineStringField(srid=_SRID)),
                ('length', models.FloatField(blank=True, null=True)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('end_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pathways_in', to='dcim.location')),
                ('start_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pathways_out', to='dcim.location')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ['name'],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AerialSpan',
            fields=[
                ('pathway_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='netbox_pathways.pathway')),
                ('aerial_type', models.CharField(blank=True, max_length=50)),
                ('attachment_height', models.FloatField(blank=True, null=True)),
                ('sag', models.FloatField(blank=True, null=True)),
                ('messenger_size', models.CharField(blank=True, max_length=50)),
                ('wind_loading', models.CharField(blank=True, max_length=50)),
                ('ice_loading', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Aerial Span',
                'verbose_name_plural': 'Aerial Spans',
            },
            bases=('netbox_pathways.pathway',),
        ),
        migrations.CreateModel(
            name='Conduit',
            fields=[
                ('pathway_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='netbox_pathways.pathway')),
                ('material', models.CharField(blank=True, max_length=50)),
                ('inner_diameter', models.FloatField(blank=True, null=True)),
                ('outer_diameter', models.FloatField(blank=True, null=True)),
                ('depth', models.FloatField(blank=True, null=True)),
                ('bank_position', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'verbose_name': 'Conduit',
                'verbose_name_plural': 'Conduits',
            },
            bases=('netbox_pathways.pathway',),
        ),
        migrations.CreateModel(
            name='DirectBuried',
            fields=[
                ('pathway_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='netbox_pathways.pathway')),
                ('burial_depth', models.FloatField(blank=True, null=True)),
                ('warning_tape', models.BooleanField(default=False)),
                ('tracer_wire', models.BooleanField(default=False)),
                ('armor_type', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Direct Buried',
                'verbose_name_plural': 'Direct Buried Paths',
            },
            bases=('netbox_pathways.pathway',),
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('structure_type', models.CharField(blank=True, max_length=50)),
                ('location', django.contrib.gis.db.models.fields.GeometryField(srid=_SRID)),
                ('elevation', models.FloatField(blank=True, null=True)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('owner', models.CharField(blank=True, max_length=100)),
                ('access_notes', models.TextField(blank=True)),
                ('comments', models.TextField(blank=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pathways_structures', to='dcim.site')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ['name'],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SiteGeometry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=_SRID)),
                ('comments', models.TextField(blank=True)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pathways_geometry', to='dcim.site')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('structure', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_geometry', to='netbox_pathways.structure')),
            ],
            options={
                'verbose_name': 'Site Geometry',
                'verbose_name_plural': 'Site Geometries',
                'ordering': ['site'],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddField(
            model_name='pathway',
            name='end_structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pathways_in', to='netbox_pathways.structure'),
        ),
        migrations.AddField(
            model_name='pathway',
            name='start_structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pathways_out', to='netbox_pathways.structure'),
        ),
        migrations.CreateModel(
            name='ConduitBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('configuration', models.CharField(blank=True, max_length=50)),
                ('total_conduits', models.PositiveIntegerField()),
                ('encasement_type', models.CharField(blank=True, max_length=50)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conduit_banks', to='netbox_pathways.structure')),
            ],
            options={
                'ordering': ['name'],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ConduitJunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('position_on_trunk', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('comments', models.TextField(blank=True)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('towards_structure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='netbox_pathways.structure')),
                ('branch_conduit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='junction_as_branch', to='netbox_pathways.conduit')),
                ('trunk_conduit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='junctions_on_trunk', to='netbox_pathways.conduit')),
            ],
            options={
                'ordering': ['name'],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddField(
            model_name='conduit',
            name='conduit_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conduits', to='netbox_pathways.conduitbank'),
        ),
        migrations.AddField(
            model_name='conduit',
            name='end_junction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conduits_to', to='netbox_pathways.conduitjunction'),
        ),
        migrations.AddField(
            model_name='conduit',
            name='start_junction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conduits_from', to='netbox_pathways.conduitjunction'),
        ),
        migrations.CreateModel(
            name='Innerduct',
            fields=[
                ('pathway_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='netbox_pathways.pathway')),
                ('size', models.CharField(max_length=50)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('position', models.CharField(blank=True, max_length=50)),
                ('parent_conduit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='innerducts', to='netbox_pathways.conduit')),
            ],
            options={
                'verbose_name': 'Innerduct',
                'verbose_name_plural': 'Innerducts',
            },
            bases=('netbox_pathways.pathway',),
        ),
        migrations.CreateModel(
            name='CableSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('enter_point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=_SRID)),
                ('exit_point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=_SRID)),
                ('slack_loop_location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=_SRID)),
                ('slack_length', models.FloatField(default=0)),
                ('comments', models.TextField(blank=True)),
                ('cable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pathway_segments', to='dcim.cable')),
                ('pathway', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cable_segments', to='netbox_pathways.pathway')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ['cable', 'sequence'],
                'unique_together': {('cable', 'sequence')},
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PathwayLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('comments', models.TextField(blank=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pathway_waypoints', to='dcim.location')),
                ('pathway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waypoints', to='netbox_pathways.pathway')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pathway_waypoints', to='dcim.site')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ['pathway', 'sequence'],
                'unique_together': {('pathway', 'sequence')},
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='structure',
            index=models.Index(fields=['structure_type'], name='netbox_path_structu_8357b3_idx'),
        ),
        migrations.AddIndex(
            model_name='structure',
            index=models.Index(fields=['site'], name='netbox_path_site_id_f3808f_idx'),
        ),
        migrations.AddIndex(
            model_name='pathway',
            index=models.Index(fields=['pathway_type'], name='netbox_path_pathway_8db3cf_idx'),
        ),
        migrations.AddIndex(
            model_name='pathway',
            index=models.Index(fields=['start_structure', 'end_structure'], name='netbox_path_start_s_eed6e8_idx'),
        ),
        migrations.AddIndex(
            model_name='conduitbank',
            index=models.Index(fields=['structure'], name='netbox_path_structu_ba9592_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='conduitjunction',
            unique_together={('trunk_conduit', 'position_on_trunk')},
        ),
        migrations.AddConstraint(
            model_name='conduit',
            constraint=models.UniqueConstraint(condition=models.Q(('bank_position__gt', ''), ('conduit_bank__isnull', False)), fields=('conduit_bank', 'bank_position'), name='unique_position_per_bank'),
        ),
    ]
