# Generated by Django 5.2.11 on 2026-03-06 20:15

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0226_add_mptt_tree_indexes'),
        ('extras', '0134_owner'),
        ('netbox_pathways', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathway',
            name='end_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pathways_in', to='dcim.location'),
        ),
        migrations.AddField(
            model_name='pathway',
            name='start_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pathways_out', to='dcim.location'),
        ),
        migrations.CreateModel(
            name='PathwayLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('comments', models.TextField(blank=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pathway_waypoints', to='dcim.location')),
                ('pathway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waypoints', to='netbox_pathways.pathway')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pathway_waypoints', to='dcim.site')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ['pathway', 'sequence'],
                'unique_together': {('pathway', 'sequence')},
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
