# Generated by Django 5.2.11 on 2026-03-06 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0226_add_mptt_tree_indexes'),
        ('netbox_pathways', '0002_pathway_end_location_pathway_start_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conduitbank',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conduit_banks', to='netbox_pathways.structure'),
        ),
        migrations.AlterField(
            model_name='conduitjunction',
            name='towards_structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='netbox_pathways.structure'),
        ),
        migrations.AlterField(
            model_name='pathway',
            name='end_structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pathways_in', to='netbox_pathways.structure'),
        ),
        migrations.AlterField(
            model_name='pathway',
            name='start_structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pathways_out', to='netbox_pathways.structure'),
        ),
        migrations.AlterField(
            model_name='pathwaylocation',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pathway_waypoints', to='dcim.location'),
        ),
        migrations.AlterField(
            model_name='pathwaylocation',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pathway_waypoints', to='dcim.site'),
        ),
    ]
