# Generated by Django 5.2.11 on 2026-03-25 01:59

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuits', '0056_gfk_indexes'),
        ('extras', '0134_owner'),
        ('netbox_pathways', '0003_structure_optional_site_dimensions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CircuitGeometry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('path', django.contrib.gis.db.models.fields.LineStringField(srid=3348)),
                ('provider_reference', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('circuit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pathways_route', to='circuits.circuit')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Circuit Geometry',
                'verbose_name_plural': 'Circuit Geometries',
                'ordering': ['circuit'],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
