# Generated by Django 5.2.11 on 2026-03-06 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_pathways', '0003_alter_conduitbank_structure_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pathway',
            name='cable_count',
        ),
        migrations.RemoveField(
            model_name='pathway',
            name='max_cable_count',
        ),
    ]
