# Generated by Django 5.2.11 on 2026-03-27 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0226_add_mptt_tree_indexes'),
        ('extras', '0134_owner'),
        ('netbox_pathways', '0004_circuit_geometry'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cablesegment',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='conduitjunction',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='pathwaylocation',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='cablesegment',
            constraint=models.UniqueConstraint(fields=('cable', 'sequence'), name='unique_cable_segment_sequence'),
        ),
        migrations.AddConstraint(
            model_name='conduitjunction',
            constraint=models.UniqueConstraint(fields=('trunk_conduit', 'position_on_trunk'), name='unique_junction_position_on_trunk'),
        ),
        migrations.AddConstraint(
            model_name='pathwaylocation',
            constraint=models.UniqueConstraint(fields=('pathway', 'sequence'), name='unique_pathway_location_sequence'),
        ),
    ]
