# Generated by Django 5.2.11 on 2026-04-03 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_pathways', '0005_replace_unique_together_with_constraints'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cablesegment',
            options={'ordering': ['cable', 'pk']},
        ),
        migrations.RemoveConstraint(
            model_name='cablesegment',
            name='unique_cable_segment_sequence',
        ),
        migrations.RemoveField(
            model_name='cablesegment',
            name='enter_point',
        ),
        migrations.RemoveField(
            model_name='cablesegment',
            name='exit_point',
        ),
        migrations.RemoveField(
            model_name='cablesegment',
            name='sequence',
        ),
    ]
