# Generated by Django 5.2.11 on 2026-04-03 16:31

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0226_add_mptt_tree_indexes'),
        ('extras', '0134_owner'),
        ('netbox_pathways', '0006_remove_cablesegment_sequence_enter_exit'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackLoop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('length', models.FloatField()),
                ('comments', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['cable', 'structure'],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AlterModelOptions(
            name='cablesegment',
            options={'ordering': ['cable', 'sequence']},
        ),
        migrations.RemoveField(
            model_name='cablesegment',
            name='slack_length',
        ),
        migrations.RemoveField(
            model_name='cablesegment',
            name='slack_loop_location',
        ),
        migrations.AddField(
            model_name='cablesegment',
            name='sequence',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='cablesegment',
            constraint=models.UniqueConstraint(fields=('cable', 'sequence'), name='unique_cable_segment_sequence'),
        ),
        migrations.AddField(
            model_name='slackloop',
            name='cable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slack_loops', to='dcim.cable'),
        ),
        migrations.AddField(
            model_name='slackloop',
            name='pathway',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slack_loops', to='netbox_pathways.pathway'),
        ),
        migrations.AddField(
            model_name='slackloop',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slack_loops', to='netbox_pathways.structure'),
        ),
        migrations.AddField(
            model_name='slackloop',
            name='tags',
            field=taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag'),
        ),
    ]
