# Generated by Django 5.2.11 on 2026-04-03 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0226_add_mptt_tree_indexes'),
        ('extras', '0134_owner'),
        ('netbox_pathways', '0006_remove_cablesegment_sequence_enter_exit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cablesegment',
            options={'ordering': ['cable', 'sequence']},
        ),
        migrations.RemoveField(
            model_name='cablesegment',
            name='slack_length',
        ),
        migrations.RemoveField(
            model_name='cablesegment',
            name='slack_loop_location',
        ),
        migrations.AddField(
            model_name='cablesegment',
            name='sequence',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='cablesegment',
            constraint=models.UniqueConstraint(fields=('cable', 'sequence'), name='unique_cable_segment_sequence'),
        ),
    ]
