# Generated by Django 5.2.11 on 2026-04-15 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_pathways', '0008_conduitbank_pathway_subclass'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='conduit',
            name='unique_position_per_bank',
        ),
        migrations.AddConstraint(
            model_name='conduit',
            constraint=models.UniqueConstraint(condition=models.Q(('bank_position__gt', ''), ('conduit_bank__isnull', False)), fields=('conduit_bank', 'bank_position'), name='unique_position_per_bank'),
        ),
    ]
