# Generated by Django 5.2.11 on 2026-04-15 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_pathways', '0009_remove_conduit_unique_position_per_bank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='status',
            field=models.CharField(default='active', max_length=50),
        ),
    ]
