# Generated by Django 5.2.11 on 2026-04-16 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0226_add_mptt_tree_indexes'),
        ('extras', '0134_owner'),
        ('netbox_pathways', '0011_rename_name_to_label'),
        ('tenancy', '0023_add_mptt_tree_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='aerialspan',
            index=models.Index(fields=['aerial_type'], name='netbox_path_aerial__66af78_idx'),
        ),
        migrations.AddIndex(
            model_name='conduit',
            index=models.Index(fields=['material'], name='netbox_path_materia_aa3008_idx'),
        ),
        migrations.AddIndex(
            model_name='structure',
            index=models.Index(fields=['status'], name='netbox_path_status_beb8d5_idx'),
        ),
    ]
