# Generated by Django 5.2.11 on 2026-04-22 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_pathways', '0013_plannedroute'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedroute',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='netbox_pathways.plannedroute'),
        ),
    ]
