# Generated by Django 5.2.13 on 2026-05-06 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_pathways', '0014_plannedroute_parent_split'),
        ('tenancy', '0023_add_mptt_tree_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathway',
            name='commissioned_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pathway',
            name='installed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='installed_pathways_pathways', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='structure',
            name='commissioned_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='structure',
            name='installed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='installed_pathways_structures', to='tenancy.tenant'),
        ),
        migrations.AddIndex(
            model_name='structure',
            index=models.Index(fields=['installed_by'], name='netbox_path_install_27b35a_idx'),
        ),
    ]
