# Generated by Django 5.2.13 on 2026-05-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_pathways', '0015_installer_and_commissioned_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cablesegment',
            name='lashed_with',
            field=models.ManyToManyField(blank=True, to='netbox_pathways.cablesegment'),
        ),
    ]
