# Generated by Django 5.2.13 on 2026-05-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_pathways', '0016_cablesegment_lashed_with'),
    ]

    operations = [
        migrations.AddField(
            model_name='conduitbank',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conduitbank',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
