# Generated by Django 5.2.13 on 2026-05-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_pathways', '0016_cablesegment_lashed_with'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aerialspan',
            name='attachment_height',
        ),
        migrations.AddField(
            model_name='aerialspan',
            name='end_attachment_height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aerialspan',
            name='start_attachment_height',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
