# Generated by Django 6.1 on 2026-10-05 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_pathways", "0024_pathway_location_endpoints_protect"),
    ]

    operations = [
        migrations.AddField(
            model_name="pathway",
            name="end_anchor",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pathways_anchored_end",
                to="netbox_pathways.structure",
            ),
        ),
        migrations.AddField(
            model_name="pathway",
            name="start_anchor",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pathways_anchored_start",
                to="netbox_pathways.structure",
            ),
        ),
    ]
